### PR TITLE
Automatic RubyGems deploys

### PR DESCRIPTION
**Pull request by larouxn**
Update deployment configuration to automatically deploy to RubyGems with ShipIt.

Changes are based on the following.
- [Shopify/bootsnap gemspec](https://github.com/Shopify/bootsnap/commit/3fff890bbe2e62b7e91f4bd09ca9b040e481fc73) (permission)
- [activemerchant/active_merchant shipit](https://github.com/activemerchant/active_merchant/blob/d032acbf55582523f9e57711ace2db5518510d8e/shipit.rubygems.yml) (filename based)

Note, the changes to the ShipIt config (remove `deploy` override) means this gem will no longer be pushed to PackagesWeb and thus, projects sourcing from there will need to be updated to pull from RubyGems instead. ([search](https://github.com/search?q=org%3AShopify+%22gem+%27pseudolocalization%27%22&type=Code))

### CODE REVIEW

**Review by shioyama — APPROVED** [review]
LGTM, I see it on rubygems: https://rubygems.org/gems/pseudolocalization

**Review by yishus — APPROVED** [review]
🙌🙌🙌

**Comment by tayre** [comment]
> Note, the changes to the ShipIt config (remove deploy override) means this gem will no longer be pushed to PackagesWeb and thus, projects sourcing from there will need to be updated to pull from RubyGems instead. (search)

Do you know the implication or risk here?

**Comment by larouxn** [comment]
> Do you know the implication or risk here?

Yep, the risk was projects that source from PackagesWeb don't get `psuedolocalization` bumps but I [searched](https://github.com/search?q=org%3AShopify+%22gem+%27pseudolocalization%27%22&type=Code) for repos sourcing from PackagesWeb and updated them to source from RubyGems, core ([PR](https://github.com/Shopify/shopify/pull/277360)) and plus-home ([PR](https://github.com/Shopify/plus-home/pull/2028)).

**Comment by tayre** [comment]
>Yep, the risk was projects that source from PackagesWeb don't get psuedolocalization bumps but I searched for repos sourcing from PackagesWeb and updated them to source from RubyGems, core (PR) and plus-home (PR).

Oh amazing - thanks for those PRs!

**Review by tayre — APPROVED** [review]

**Pull request merged**
